# Generated by Django 4.2 on 2023-09-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_userau_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tabSalutation',
            },
        ),
    ]
