# Generated by Django 4.2 on 2023-09-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_salutation_options_alter_userau_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
