# Generated by Django 4.2 on 2023-09-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(db_column='gender_1', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Salutation',
                'db_table': 'tabGender',
            },
        ),
    ]
