# Generated by Django 4.2 on 2023-09-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(db_column='gender', max_length=255, unique=True),
        ),
    ]
