# Generated by Django 4.2 on 2023-09-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_gender_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Gender'},
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(db_column='gender', db_comment='Person Gender', help_text='Gender of the Person.', max_length=255, unique=True),
        ),
    ]
