# Generated by Django 4.2 on 2023-09-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_gender_options_alter_gender_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(db_column='gender', db_comment='Person Gender', help_text='Gender of the Person.', max_length=255, unique=True, verbose_name='Person Gender'),
        ),
    ]
