# Generated by Django 4.2 on 2023-09-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_leadsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('name', models.CharField(db_column='name', help_text='Name of the Teritory', max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Teritory Name')),
                ('parent_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.territory')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Mention the customer name it may individual or company name', max_length=255, verbose_name='Customer Name')),
                ('customer_type', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual')], default='Company', help_text='It may be a individual or', max_length=50, verbose_name='Customer Type')),
                ('salutation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.salutation')),
            ],
        ),
    ]
