# Generated by Django 4.2 on 2023-09-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_territory_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='territory',
            options={'verbose_name': 'Teritory or Region'},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='tabCustomer',
        ),
        migrations.AlterModelTable(
            name='territory',
            table='tabTerritory',
        ),
    ]
