# Generated by Django 4.2 on 2023-09-21 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_customer_options_alter_territory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='parent_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.territory'),
        ),
    ]
