# Generated by Django 4.2 on 2023-09-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_territory_parent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='parent_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.territory'),
        ),
    ]
