# Generated by Django 4.2 on 2023-09-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_territory_parent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='parent_name',
            field=models.ForeignKey(blank=True, default='All Territories', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='crm.territory'),
        ),
    ]
