# Generated by Django 4.2 on 2023-09-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_customergroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_group',
            field=models.ForeignKey(blank=True, db_column='customer_group', max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customergroup'),
        ),
        migrations.AddField(
            model_name='customer',
            name='territory',
            field=models.ForeignKey(blank=True, db_column='territory', max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.territory'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='salutation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.salutation'),
        ),
    ]
