# Generated by Django 4.2 on 2023-10-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='type',
            field=models.CharField(choices=[('M', 'MASTERS'), ('R', 'REPORT')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
